### ISSUE TITLE
Example video missing from ZIP download

### ISSUE THREAD

**Issue by stekra** [woistjadefox/exhibition-attraction-screen#2]
The beautiful example video unfortunately does not get included when manually downloading the repo as an archive.
[It looks like this can be configured in the repo settings.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository)
Nothing dramatic, but maybe worth doing for convenience — of course only if your LFS bandwidth quota can bear it.

Otherwise tested on the newest LTS as of today and works great 👍

**Comment by woistjadefox** [comment]
Thanks for the info, I have updated the repo settings.
